### GET Products
GET http://localhost:8080/api/products

### Create Products
POST http://localhost:8080/api/products
Content-Type: application/json

{
  "name": "PC",
  "price": 1023.5,
  "stock": 4
}

### Delete Products
DELETE http://localhost:8080/api/products/698bbb3ede6aa654c804c36c