### GET Users
GET http://localhost:8080/api/users

### Create User
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "name": "Pep",
  "email": "pep@mail.com"
}

### Delete User
DELETE http://localhost:8080/api/users/698bbb8dde6aa654c804c36d